//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikasss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialSuppliers = new HashSet<MaterialSuppliers>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> QuantityInStock { get; set; }
        public Nullable<double> MinQuantity { get; set; }
        public Nullable<double> QuantityInPackage { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSuppliers> MaterialSuppliers { get; set; }
    }
}
