//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikasss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.MaterialSuppliers = new HashSet<MaterialSuppliers>();
        }
    
        public int SuppliersID { get; set; }
        public string SupplierName { get; set; }
        public int SuppliersTypeID { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> DateWorkSupplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSuppliers> MaterialSuppliers { get; set; }
        public virtual SuppliersTypes SuppliersTypes { get; set; }
    }
}
